apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-kubecore-schema-registry
spec:
  compositeTypeRef:
    apiVersion: platform.kubecore.io/v1alpha1
    kind: XSchemaRegistry
  mode: Pipeline
  pipeline:
  - step: schema-registry-discovery
    functionRef:
      name: function-kubecore-schema-registry
    input:
      apiVersion: template.fn.crossplane.io/v1beta1
      kind: Input
      enableTransitiveDiscovery: true
      traversalDepth: 3
      includeFullSchema: true
