---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-kubecore-schema-registry
  annotations:
    # This tells crossplane beta render to connect to the function locally.
    render.crossplane.io/runtime: Development
spec:
  # This is ignored when using the Development runtime.
  package: function-kubecore-schema-registry
---
# Function input configuration
apiVersion: template.fn.crossplane.io/v1beta1
kind: Input
metadata:
  name: schema-registry-config
spec:
  enableTransitiveDiscovery: true
  traversalDepth: 3
  includeFullSchema: true
