# Test GitHubProject with githubProviderRef for scope filtering fixes
apiVersion: github.platform.kubecore.io/v1alpha1
kind: GitHubProject
metadata:
  name: demo-project
  namespace: test
  labels:
    team: platform
    environment: test
spec:
  repository: "acme-corp/demo-project"
  branch: "main"
  path: "manifests"
  visibility: internal
  
  # This reference should be detected with high confidence (0.95)
  githubProviderRef:
    name: "github-provider-main"
  
  # These fields should be filtered out due to low confidence + empty TargetKind
  owner: "platform-team"  # Should create low confidence heuristic match
  template:
    name: "standard-template"
    repositorySource:
      template:
        owner: "template-org"  # Should create low confidence heuristic match

---
# Test GithubProvider that should be discovered
apiVersion: github.platform.kubecore.io/v1alpha1
kind: GithubProvider
metadata:
  name: github-provider-main
  # No namespace - this is cluster-scoped
  labels:
    provider: github
    environment: production
spec:
  endpoint: "https://api.github.com"
  organization: "acme-corp"
  credentials:
    secretRef:
      name: "github-token"
      namespace: "crossplane-system"
  
  # Additional config
  webhookURL: "https://webhook.example.com/github"
  enableWebhooks: true