apiVersion: v1
data:
  discovery-method: direct-match
  execution-time: "2025-08-21T15:23:14Z"
  githubproject-spec.yaml: "apiVersion: github.platform.kubecore.io/v1alpha1\nkind:
    GitHubProject\nmetadata:\n  name: demo-project\n  namespace: test\nspec:\n            compositeDeletePolicy:
    Background\n            compositionRef:\n                name: githubprojects.github.platform.kubecore.io\n
    \           compositionRevisionRef:\n                name: githubprojects.github.platform.kubecore.io-ffae40f\n
    \           description: Testing scope fixes - updated at $(date)\n            githubProviderRef:\n
    \               name: gh-test-namespace\n                namespace: test\n            repositorySource:\n
    \               template:\n                    includeAllBranches: false\n                    owner:
    novelcore\n                    repository: kubeproject-template\n                type:
    template\n            resourceRef:\n                apiVersion: github.platform.kubecore.io/v1alpha1\n
    \               kind: XGitHubProject\n                name: demo-project-zpmwk\n
    \           teamConfiguration:\n                parentTeams:\n                    main:
    \"12972099\"\n                teamMembers:\n                    business:\n                        -
    role: member\n                          username: dfourakis\n                    ops:\n
    \                       - role: maintainer\n                          username:
    AbstractVersion\n                    software:\n                        - role:
    maintainer\n                          username: AbstractVersion\n            visibility:
    private\n            \n"
  resource-count: "1"
  test-description: Fetches a specific GitHubProject resource directly by name
  test-name: TestDirect
  test-result: SUCCESS
  test-type: Direct Match on GitHubProject
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","data":{"discovery-method":"direct-match","execution-time":"2025-08-21T15:23:14Z","githubproject-spec.yaml":"apiVersion:
      github.platform.kubecore.io/v1alpha1\nkind: GitHubProject\nmetadata:\n  name:
      demo-project\n  namespace: test\nspec:\n            compositeDeletePolicy: Background\n            compositionRef:\n                name:
      githubprojects.github.platform.kubecore.io\n            compositionRevisionRef:\n                name:
      githubprojects.github.platform.kubecore.io-ffae40f\n            description:
      Testing scope fixes - updated at $(date)\n            githubProviderRef:\n                name:
      gh-test-namespace\n                namespace: test\n            repositorySource:\n                template:\n                    includeAllBranches:
      false\n                    owner: novelcore\n                    repository:
      kubeproject-template\n                type: template\n            resourceRef:\n                apiVersion:
      github.platform.kubecore.io/v1alpha1\n                kind: XGitHubProject\n                name:
      demo-project-zpmwk\n            teamConfiguration:\n                parentTeams:\n                    main:
      \"12972099\"\n                teamMembers:\n                    business:\n                        -
      role: member\n                          username: dfourakis\n                    ops:\n                        -
      role: maintainer\n                          username: AbstractVersion\n                    software:\n                        -
      role: maintainer\n                          username: AbstractVersion\n            visibility:
      private\n            \n","resource-count":"1","test-description":"Fetches a
      specific GitHubProject resource directly by name","test-name":"TestDirect","test-result":"SUCCESS","test-type":"Direct
      Match on GitHubProject"},"kind":"ConfigMap","metadata":{"labels":{"kubecore.io/discovery-method":"direct","kubecore.io/test":"TestDirect","test-type":"direct-match"},"name":"test-direct-result","namespace":"default"}}'
  creationTimestamp: "2025-08-21T15:22:07Z"
  labels:
    kubecore.io/discovery-method: direct
    kubecore.io/test: TestDirect
    test-type: direct-match
  name: test-direct-result
  namespace: default
  resourceVersion: "2766376"
  uid: 1363af35-c6fd-42df-bbe8-a0ea6ee56a93
