# XRD Definition for Reference Resolution Test (CRITICAL BUG FIX VALIDATION)
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xreferenceresolutiontests.test.kubecore.platform.io
spec:
  group: test.kubecore.platform.io
  names:
    kind: XReferenceResolutionTest
    plural: xreferenceresolutiontests
  claimNames:
    kind: ReferenceResolutionTest
    plural: referenceresolutiontests
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              testName:
                type: string
                description: "Name of the reference resolution test"
              expectedResources:
                type: integer
                description: "Expected number of resources to discover"
                default: 2
              maxDepth:
                type: integer
                description: "Maximum traversal depth"
                default: 3
            required:
            - testName
          status:
            type: object
            properties:
              fetchSummary:
                type: object
                properties:
                  totalRequested:
                    type: integer
                  successful:
                    type: integer
                  failed:
                    type: integer
                  skipped:
                    type: integer
                  executionTime:
                    type: string
              referenceResolutionResults:
                type: object
                properties:
                  discoveredResources:
                    type: integer
                    description: "Total resources discovered"
                  maxDepthReached:
                    type: integer
                    description: "Maximum depth reached"
                  referencesResolved:
                    type: integer
                    description: "Number of references successfully resolved"
                  testStatus:
                    type: string
                    enum: ["PASS", "FAIL", "PARTIAL"]
                  executionTime:
                    type: string
                    description: "Test execution duration"
---
# Reference Resolution Test Composition (CRITICAL BUG FIX VALIDATION)
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xreferenceresolutiontest.test.kubecore.platform.io
spec:
  compositeTypeRef:
    apiVersion: test.kubecore.platform.io/v1alpha1
    kind: XReferenceResolutionTest

  mode: Pipeline

  pipeline:
  # CRITICAL TEST: Phase 3 Reference Resolution Bug Fix
  - step: test-reference-resolution-fix
    functionRef:
      name: function-kubecore-schema-registry
    input:
      apiVersion: registry.fn.crossplane.io/v1beta1
      kind: Input
      phase3Features: true
      fetchTimeout: "30s"
      maxConcurrentFetches: 5
      fetchResources:
      # CRITICAL: Test GitHubProject -> GithubProvider reference resolution
      - into: "projectWithProvider"
        name: "demo-project"
        namespace: "test"
        apiVersion: "github.platform.kubecore.io/v1alpha1"
        kind: "GitHubProject"
        optional: false
      traversalConfig:
        enabled: true
        maxDepth: 3
        maxResources: 50
        timeout: "30s"
        direction: "forward"  # Follow references from GitHubProject
        scopeFilter:
          platformOnly: true
          includeAPIGroups:
            - "github.platform.kubecore.io"
          crossNamespaceEnabled: true
        referenceResolution:
          enableDynamicCRDs: true
          followCustomReferences: true
          minConfidenceThreshold: 0.5
          additionalPatterns:
            - pattern: "githubProviderRef*"
              targetKind: "GithubProvider"
              targetGroup: "github.platform.kubecore.io"
              confidence: 0.9
        cycleHandling:
          detectionEnabled: true
          onCycleDetected: "continue"
        performance:
          maxConcurrentRequests: 5
          requestTimeout: "5s"
          enableMetrics: true
          resourceDeduplication: true

  # TEST 2: Bidirectional Discovery (Reverse Reference)
  - step: test-bidirectional-discovery
    functionRef:
      name: function-kubecore-schema-registry
    input:
      apiVersion: registry.fn.crossplane.io/v1beta1
      kind: Input
      phase3Features: true
      fetchTimeout: "30s"
      maxConcurrentFetches: 5
      fetchResources:
      # Start from GithubProvider and find dependents
      - into: "providerWithDependents"
        name: "gh-default"
        apiVersion: "github.platform.kubecore.io/v1alpha1"
        kind: "GithubProvider"
        optional: false
      traversalConfig:
        enabled: true
        maxDepth: 3
        maxResources: 50
        timeout: "30s"
        direction: "bidirectional"  # Find both dependencies and dependents
        scopeFilter:
          platformOnly: true
          includeAPIGroups:
            - "github.platform.kubecore.io"
          crossNamespaceEnabled: true
        referenceResolution:
          enableDynamicCRDs: true
          followCustomReferences: true
          minConfidenceThreshold: 0.5
        performance:
          maxConcurrentRequests: 5
          enableMetrics: true

  # TEST 3: Performance and DAG Construction
  - step: test-performance-dag
    functionRef:
      name: function-kubecore-schema-registry
    input:
      apiVersion: registry.fn.crossplane.io/v1beta1
      kind: Input
      phase3Features: true
      fetchTimeout: "30s"
      maxConcurrentFetches: 5
      fetchResources:
      - into: "performanceTest"
        name: "demo-project"
        namespace: "test"
        apiVersion: "github.platform.kubecore.io/v1alpha1"
        kind: "GitHubProject"
        optional: false
      traversalConfig:
        enabled: true
        maxDepth: 3
        maxResources: 50
        timeout: "30s"
        direction: "forward"
        scopeFilter:
          platformOnly: true
          includeAPIGroups:
            - "github.platform.kubecore.io"
        batchConfig:
          enabled: true
          batchSize: 10
          maxConcurrentBatches: 2
        cacheConfig:
          enabled: true
          ttl: "5m"
          maxSize: 100
          strategy: "lru"
        referenceResolution:
          enableDynamicCRDs: true
          followCustomReferences: true
          minConfidenceThreshold: 0.5
        performance:
          enableMetrics: true
          resourceDeduplication: true
          memoryLimits:
            maxGraphSize: 10485760
            maxCacheSize: 2097152
            gcThreshold: 20971520