# XRD Definition for Schema Registry Phase 3 Test
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xschemaregistryphase3tests.test.kubecore.platform.io
spec:
  group: test.kubecore.platform.io
  names:
    kind: XSchemaRegistryPhase3Test
    plural: xschemaregistryphase3tests
  claimNames:
    kind: SchemaRegistryPhase3Test
    plural: schemaregistryphase3tests
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              testName:
                type: string
                description: "Name identifier for this test run"
              description:
                type: string
                description: "Description of what this test validates"
              phase3Enabled:
                type: boolean
                description: "Whether to test Phase 3 features"
                default: true
              testScenario:
                type: string
                description: "Test scenario to execute"
                enum: ["complete-topology", "security-boundary", "cycle-detection", "performance-optimization", "reference-resolution", "memory-management", "input-validation"]
              rootResource:
                type: object
                description: "Root resource configuration for transitive discovery"
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                  apiVersion:
                    type: string
                  kind:
                    type: string
                required:
                - name
                - apiVersion
                - kind
            required:
            - testName
            - testScenario
          status:
            type: object
            properties:
              fetchSummary:
                type: object
                properties:
                  totalRequested:
                    type: integer
                  successful:
                    type: integer
                  failed:
                    type: integer
                  skipped:
                    type: integer
                  executionTime:
                    type: string
              phase3Results:
                type: object
                properties:
                  traversalStats:
                    type: object
                    properties:
                      totalDiscovered:
                        type: integer
                      maxDepthReached:
                        type: integer
                      cyclesDetected:
                        type: integer
                      platformResourcesOnly:
                        type: boolean
                      batchesProcessed:
                        type: integer
                      cacheHitRate:
                        type: number
                      memoryUsageBytes:
                        type: integer
                      executionTimeMs:
                        type: integer
                  graphMetadata:
                    type: object
                    properties:
                      nodeCount:
                        type: integer
                      edgeCount:
                        type: integer
                      stronglyConnectedComponents:
                        type: integer
                  securityValidation:
                    type: object
                    properties:
                      platformBoundaryRespected:
                        type: boolean
                      excludedResourcesCount:
                        type: integer
                      allowedAPIGroups:
                        type: array
                        items:
                          type: string
---
# Phase 3 Test Composition
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xschemaregistryphase3test.test.kubecore.platform.io
spec:
  compositeTypeRef:
    apiVersion: test.kubecore.platform.io/v1alpha1
    kind: XSchemaRegistryPhase3Test

  mode: Pipeline

  pipeline:
  # Step 1: Phase 3 Transitive Discovery - Complete Application Topology
  - step: phase3-transitive-discovery
    functionRef:
      name: function-kubecore-schema-registry
    input:
      apiVersion: registry.fn.crossplane.io/v1beta1
      kind: Input
      phase3Features: true
      fetchTimeout: "30s"
      maxConcurrentFetches: 10
      fetchResources:
      # Root resource for transitive discovery
      - into: rootAppResource
        name: art-api
        namespace: default
        apiVersion: app.kubecore.io/v1alpha1
        kind: App
        optional: false
      traversalConfig:
        enabled: true
        maxDepth: -1                        # Unlimited depth
        maxResources: 100                   # Safety limit
        timeout: "30s"
        direction: "bidirectional"          # Find dependencies and dependents
        scopeFilter:
          platformOnly: true                # CRITICAL: Only platform resources
          includeAPIGroups:
            - "*.kubecore.io"
            - "platform.kubecore.io"
            - "github.platform.kubecore.io"
            - "app.kubecore.io"
          excludeKinds:                     # Infrastructure resources excluded
            - "Secret"
            - "ConfigMap"
            - "ServiceAccount"
            - "ClusterSecretStore"
            - "PersistentVolumeClaim"
          crossNamespaceEnabled: true
        batchConfig:
          enabled: true
          batchSize: 10
          maxConcurrentBatches: 3
          sameDepthBatching: true
          batchTimeout: "5s"
        cacheConfig:
          enabled: true
          ttl: "5m"
          maxSize: 1000
          strategy: "lru"
        referenceResolution:
          enableDynamicCRDs: true
          followOwnerReferences: true
          followCustomReferences: true
          skipMissingReferences: true
          minConfidenceThreshold: 0.5
          additionalPatterns:
            - pattern: "*ClusterRef"
              targetKind: "KubeCluster"
              targetGroup: "platform.kubecore.io"
              confidence: 0.9
            - pattern: "*EnvRef"
              targetKind: "KubEnv"
              targetGroup: "platform.kubecore.io"
              confidence: 0.9
        cycleHandling:
          detectionEnabled: true
          onCycleDetected: "continue"       # Continue traversal on cycle
          maxCycles: 10
          reportCycles: true
        performance:
          maxConcurrentRequests: 10
          requestTimeout: "2s"
          enableMetrics: true
          resourceDeduplication: true
          memoryLimits:
            maxGraphSize: 52428800          # 50MB graph limit
            maxCacheSize: 10485760          # 10MB cache limit
            gcThreshold: 83886080           # 80MB GC threshold

  # Step 2: Phase 3 Platform Security Boundary Test
  - step: phase3-security-boundary
    functionRef:
      name: function-kubecore-schema-registry
    input:
      apiVersion: registry.fn.crossplane.io/v1beta1
      kind: Input
      phase3Features: true
      fetchTimeout: "20s"
      maxConcurrentFetches: 5
      fetchResources:
      # Test platform boundary enforcement starting from KubeCluster
      - into: securityTestRoot
        name: demo-cluster
        namespace: test
        apiVersion: platform.kubecore.io/v1alpha1
        kind: KubeCluster
        optional: false
      traversalConfig:
        enabled: true
        maxDepth: 3
        maxResources: 50
        timeout: "20s"
        direction: "forward"
        scopeFilter:
          platformOnly: true                # STRICT: Only platform resources
          includeAPIGroups:
            - "platform.kubecore.io"        # Only core platform
          excludeKinds:                     # All infrastructure excluded
            - "Secret"
            - "ConfigMap"
            - "ServiceAccount"
            - "ClusterSecretStore"
            - "PersistentVolumeClaim"
            - "PersistentVolume"
            - "Pod"
            - "Service"
            - "Deployment"
          crossNamespaceEnabled: false      # Stay within namespace
        referenceResolution:
          followOwnerReferences: false      # Don't follow k8s owner refs
          followCustomReferences: true      # Only platform custom refs
          minConfidenceThreshold: 0.8       # High confidence
        cycleHandling:
          detectionEnabled: true
          onCycleDetected: "fail"           # Fail on cycles in platform
        performance:
          maxConcurrentRequests: 5          # Conservative
          enableMetrics: true

  # Step 3: Phase 3 Cycle Detection Test
  - step: phase3-cycle-detection
    functionRef:
      name: function-kubecore-schema-registry
    input:
      apiVersion: registry.fn.crossplane.io/v1beta1
      kind: Input
      phase3Features: true
      fetchTimeout: "15s"
      maxConcurrentFetches: 3
      fetchResources:
      # Test cycle detection in resource chain
      - into: cycleTestRoot
        name: demo-kubesystem
        namespace: test
        apiVersion: platform.kubecore.io/v1alpha1
        kind: KubeSystem
        optional: false
      traversalConfig:
        enabled: true
        maxDepth: 5
        maxResources: 30
        timeout: "15s"
        direction: "bidirectional"          # Both directions for cycles
        scopeFilter:
          platformOnly: true
          includeAPIGroups:
            - "platform.kubecore.io"
          crossNamespaceEnabled: true
        cycleHandling:
          detectionEnabled: true             # ENABLE cycle detection
          onCycleDetected: "continue"        # Continue on cycle
          maxCycles: 5
          reportCycles: true                 # Report cycle details
        referenceResolution:
          followOwnerReferences: true
          followCustomReferences: true
          minConfidenceThreshold: 0.6
        performance:
          enableMetrics: true
          resourceDeduplication: true

  # Step 4: Phase 3 Performance Optimization Test
  - step: phase3-performance-optimization
    functionRef:
      name: function-kubecore-schema-registry
    input:
      apiVersion: registry.fn.crossplane.io/v1beta1
      kind: Input
      phase3Features: true
      fetchTimeout: "25s"
      maxConcurrentFetches: 8
      fetchResources:
      # Test performance with multiple root resources
      - into: performanceTestRoot
        name: demo-dev
        namespace: test
        apiVersion: platform.kubecore.io/v1alpha1
        kind: KubEnv
        optional: false
      traversalConfig:
        enabled: true
        maxDepth: 4
        maxResources: 75
        timeout: "25s"
        direction: "bidirectional"
        scopeFilter:
          platformOnly: true
          includeAPIGroups:
            - "*.kubecore.io"
          crossNamespaceEnabled: true
        batchConfig:
          enabled: true                      # TEST batch processing
          batchSize: 5                       # Smaller batches
          maxConcurrentBatches: 2
          sameDepthBatching: true
          batchTimeout: "3s"
        cacheConfig:
          enabled: true                      # TEST caching
          ttl: "2m"
          maxSize: 500
          strategy: "lru"
        referenceResolution:
          enableDynamicCRDs: true
          followOwnerReferences: true
          followCustomReferences: true
          minConfidenceThreshold: 0.7
        performance:
          maxConcurrentRequests: 8           # TEST concurrency
          requestTimeout: "3s"
          enableMetrics: true                # CAPTURE metrics
          resourceDeduplication: true
          memoryLimits:
            maxGraphSize: 26214400           # 25MB limit
            maxCacheSize: 5242880            # 5MB cache
            gcThreshold: 41943040            # 40MB GC