# Test Case 1: Phase 2 Comprehensive Test - All Features
apiVersion: test.kubecore.platform.io/v1alpha1
kind: SchemaRegistryPhase2Test
metadata:
  name: phase2-comprehensive-test
  namespace: default
spec:
  testName: phase2-comprehensive
  description: "Comprehensive test covering Phase 2 label-based and expression-based discovery with backward compatibility"
  phase2Enabled: true
  testScenario: "comprehensive"
---
# Test Case 2: Backward Compatibility Test - Phase 1 Features Only
apiVersion: test.kubecore.platform.io/v1alpha1
kind: SchemaRegistryPhase2Test
metadata:
  name: phase1-backward-compatibility-test
  namespace: default
spec:
  testName: phase1-backward-compatibility
  description: "Test backward compatibility - Phase 1 direct resource fetch without Phase 2 features"
  phase2Enabled: false
  testScenario: "backward-compatibility"
---
# Test Case 3: Label-Based Discovery Focus Test
apiVersion: test.kubecore.platform.io/v1alpha1
kind: SchemaRegistryPhase2Test
metadata:
  name: phase2-label-discovery-test
  namespace: default
spec:
  testName: phase2-label-discovery
  description: "Focus test for Phase 2 label-based resource discovery with multiple operators and constraints"
  phase2Enabled: true
  testScenario: "label-discovery"
---
# Test Case 4: Expression-Based Discovery Focus Test
apiVersion: test.kubecore.platform.io/v1alpha1
kind: SchemaRegistryPhase2Test
metadata:
  name: phase2-expression-discovery-test
  namespace: default
spec:
  testName: phase2-expression-discovery
  description: "Focus test for Phase 2 expression-based resource discovery with all operators"
  phase2Enabled: true
  testScenario: "expression-discovery"
---
# Test Case 5: Advanced Features Test
apiVersion: test.kubecore.platform.io/v1alpha1
kind: SchemaRegistryPhase2Test
metadata:
  name: phase2-advanced-features-test
  namespace: default
spec:
  testName: phase2-advanced-features
  description: "Test advanced Phase 2 features: namespace selection, sorting, constraints, batch optimization"
  phase2Enabled: true
  testScenario: "advanced-features"
---
# Test Case 6: Error Handling and Edge Cases Test
apiVersion: test.kubecore.platform.io/v1alpha1
kind: SchemaRegistryPhase2Test
metadata:
  name: phase2-error-handling-test
  namespace: default
spec:
  testName: phase2-error-handling
  description: "Test Phase 2 error handling: constraint violations, invalid selectors, missing resources"
  phase2Enabled: true
  testScenario: "error-handling"
---
# Test Case 7: Performance and Scalability Test
apiVersion: test.kubecore.platform.io/v1alpha1
kind: SchemaRegistryPhase2Test
metadata:
  name: phase2-performance-test
  namespace: default
spec:
  testName: phase2-performance
  description: "Test Phase 2 performance characteristics and scalability with large result sets"
  phase2Enabled: true
  testScenario: "performance"
