# Test Case 1: Reference Resolution Bug Fix Validation
apiVersion: test.kubecore.platform.io/v1alpha1
kind: XReferenceResolutionTest
metadata:
  name: reference-resolution-fix-test
  namespace: default
spec:
  testName: "reference-resolution-bug-fix"
  expectedResources: 2
  maxDepth: 3
