# Test Case 1: Phase 3 Complete Application Topology Discovery
apiVersion: test.kubecore.platform.io/v1alpha1
kind: SchemaRegistryPhase3Test
metadata:
  name: phase3-complete-topology-test
  namespace: default
spec:
  testName: phase3-complete-topology
  description: "Test complete application topology discovery with transitive relationships and platform security boundaries"
  phase3Enabled: true
  testScenario: "complete-topology"
  rootResource:
    name: art-api
    namespace: default
    apiVersion: app.kubecore.io/v1alpha1
    kind: App
---
# Test Case 2: Phase 3 Platform Security Boundary Enforcement 
apiVersion: test.kubecore.platform.io/v1alpha1
kind: SchemaRegistryPhase3Test
metadata:
  name: phase3-security-boundary-test
  namespace: default
spec:
  testName: phase3-security-boundary
  description: "Test platform security boundary enforcement - only *.kubecore.io resources allowed"
  phase3Enabled: true
  testScenario: "security-boundary"
  rootResource:
    name: demo-cluster
    namespace: test
    apiVersion: platform.kubecore.io/v1alpha1
    kind: KubeCluster
---
# Test Case 3: Phase 3 Cycle Detection Test
apiVersion: test.kubecore.platform.io/v1alpha1
kind: SchemaRegistryPhase3Test
metadata:
  name: phase3-cycle-detection-test
  namespace: default
spec:
  testName: phase3-cycle-detection
  description: "Test cycle detection in bidirectional resource traversal with DFS algorithm"
  phase3Enabled: true
  testScenario: "cycle-detection"
  rootResource:
    name: demo-kubesystem
    namespace: test
    apiVersion: platform.kubecore.io/v1alpha1
    kind: KubeSystem
---
# Test Case 4: Phase 3 Performance Optimization Test
apiVersion: test.kubecore.platform.io/v1alpha1
kind: SchemaRegistryPhase3Test
metadata:
  name: phase3-performance-test
  namespace: default
spec:
  testName: phase3-performance-optimization
  description: "Test performance optimization features: batching, caching, concurrent processing"
  phase3Enabled: true
  testScenario: "performance-optimization"
  rootResource:
    name: demo-dev
    namespace: test
    apiVersion: platform.kubecore.io/v1alpha1
    kind: KubEnv
---
# Test Case 5: Phase 3 Reference Resolution Test
apiVersion: test.kubecore.platform.io/v1alpha1
kind: SchemaRegistryPhase3Test
metadata:
  name: phase3-reference-resolution-test
  namespace: default
spec:
  testName: phase3-reference-resolution
  description: "Test multiple reference resolution types: owner refs, custom refs, cross-namespace"
  phase3Enabled: true
  testScenario: "reference-resolution"
  rootResource:
    name: demo-project
    namespace: test
    apiVersion: github.platform.kubecore.io/v1alpha1
    kind: GitHubProject