apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-registry-template-test
data:
  # Example 1: Iterate over all discovered resources
  discovered-resources: |
{{ range .context.schemaRegistryResults.discoveredResources }}    - name: {{ .name }}
      kind: {{ .kind }}
      apiVersion: {{ .apiVersion }}
      namespace: {{ .namespace }}
      referencedBy: {{ .referencedBy }}
      depth: {{ .depth }}
      source: {{ .source }}
{{ if .parentResource }}      parentResource: {{ .parentResource }}
{{ end }}{{ end }}
  
  # Example 2: Access resources by Kind
  github-projects: |
{{ $githubProjects := index .context.schemaRegistryResults.resourcesByKind "GitHubProject" }}{{ range $githubProjects }}    - project: {{ .name }}
      namespace: {{ .namespace }}
{{ end }}
  
  # Example 3: Reference chains
  reference-chains: |
{{ range .context.schemaRegistryResults.referenceChains }}    - path: {{ .path }}
      resources: {{ .resources }}
      kinds: {{ .kinds }}
{{ end }}
  
  # Example 4: Conditional resource processing
  has-github-provider: |
{{ if index .context.schemaRegistryResults.resourcesByKind "GithubProvider" }}    GithubProvider resources found:
{{ range index .context.schemaRegistryResults.resourcesByKind "GithubProvider" }}      - {{ .name }} (depth: {{ .depth }})
{{ end }}{{ else }}    No GithubProvider resources found
{{ end }}
  
  # Example 5: Discovery statistics
  discovery-stats: |
    Total Resources Found: {{ .context.schemaRegistryResults.discoveryStats.totalResourcesFound }}
    Total Schemas Retrieved: {{ .context.schemaRegistryResults.discoveryStats.totalSchemasRetrieved }}
    Max Depth Reached: {{ .context.schemaRegistryResults.discoveryStats.maxDepthReached }}
    Execution Time: {{ .context.schemaRegistryResults.discoveryStats.executionTimeMs }}ms
  
  # Example 6: Schema information
  resource-schemas: |
{{ range $kind, $schema := .context.schemaRegistryResults.resourceSchemas }}    {{ $kind }}:
      apiVersion: {{ $schema.apiVersion }}
      requiredFields: {{ $schema.requiredFields }}
{{ if $schema.referenceFields }}      referenceFields:
{{ range $schema.referenceFields }}        - name: {{ .name }}
          targetKind: {{ .targetKind }}
          required: {{ .required }}
{{ end }}{{ end }}{{ end }}