//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BatchConfig) DeepCopyInto(out *BatchConfig) {
	*out = *in
	if in.BatchTimeout != nil {
		in, out := &in.BatchTimeout, &out.BatchTimeout
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BatchConfig.
func (in *BatchConfig) DeepCopy() *BatchConfig {
	if in == nil {
		return nil
	}
	out := new(BatchConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheConfig) DeepCopyInto(out *CacheConfig) {
	*out = *in
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheConfig.
func (in *CacheConfig) DeepCopy() *CacheConfig {
	if in == nil {
		return nil
	}
	out := new(CacheConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CycleHandlingConfig) DeepCopyInto(out *CycleHandlingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CycleHandlingConfig.
func (in *CycleHandlingConfig) DeepCopy() *CycleHandlingConfig {
	if in == nil {
		return nil
	}
	out := new(CycleHandlingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicLabel) DeepCopyInto(out *DynamicLabel) {
	*out = *in
	if in.Transform != nil {
		in, out := &in.Transform, &out.Transform
		*out = new(LabelTransform)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicLabel.
func (in *DynamicLabel) DeepCopy() *DynamicLabel {
	if in == nil {
		return nil
	}
	out := new(DynamicLabel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Expression) DeepCopyInto(out *Expression) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Expression.
func (in *Expression) DeepCopy() *Expression {
	if in == nil {
		return nil
	}
	out := new(Expression)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Input) DeepCopyInto(out *Input) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.FetchResources != nil {
		in, out := &in.FetchResources, &out.FetchResources
		*out = make([]ResourceRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FetchTimeout != nil {
		in, out := &in.FetchTimeout, &out.FetchTimeout
		*out = new(string)
		**out = **in
	}
	if in.MaxConcurrentFetches != nil {
		in, out := &in.MaxConcurrentFetches, &out.MaxConcurrentFetches
		*out = new(int)
		**out = **in
	}
	if in.Phase2Features != nil {
		in, out := &in.Phase2Features, &out.Phase2Features
		*out = new(bool)
		**out = **in
	}
	if in.Phase3Features != nil {
		in, out := &in.Phase3Features, &out.Phase3Features
		*out = new(bool)
		**out = **in
	}
	if in.TraversalConfig != nil {
		in, out := &in.TraversalConfig, &out.TraversalConfig
		*out = new(TraversalConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.XRLabels != nil {
		in, out := &in.XRLabels, &out.XRLabels
		*out = new(XRLabelConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Input.
func (in *Input) DeepCopy() *Input {
	if in == nil {
		return nil
	}
	out := new(Input)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Input) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelSelector) DeepCopyInto(out *LabelSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MatchExpressions != nil {
		in, out := &in.MatchExpressions, &out.MatchExpressions
		*out = make([]LabelSelectorRequirement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelSelector.
func (in *LabelSelector) DeepCopy() *LabelSelector {
	if in == nil {
		return nil
	}
	out := new(LabelSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelSelectorRequirement) DeepCopyInto(out *LabelSelectorRequirement) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelSelectorRequirement.
func (in *LabelSelectorRequirement) DeepCopy() *LabelSelectorRequirement {
	if in == nil {
		return nil
	}
	out := new(LabelSelectorRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelTransform) DeepCopyInto(out *LabelTransform) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = new(TransformOptions)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelTransform.
func (in *LabelTransform) DeepCopy() *LabelTransform {
	if in == nil {
		return nil
	}
	out := new(LabelTransform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchStrategy) DeepCopyInto(out *MatchStrategy) {
	*out = *in
	if in.MinMatches != nil {
		in, out := &in.MinMatches, &out.MinMatches
		*out = new(int)
		**out = **in
	}
	if in.MaxMatches != nil {
		in, out := &in.MaxMatches, &out.MaxMatches
		*out = new(int)
		**out = **in
	}
	if in.StopOnFirst != nil {
		in, out := &in.StopOnFirst, &out.StopOnFirst
		*out = new(bool)
		**out = **in
	}
	if in.SortBy != nil {
		in, out := &in.SortBy, &out.SortBy
		*out = make([]SortCriteria, len(*in))
		copy(*out, *in)
	}
	if in.FailOnConstraintViolation != nil {
		in, out := &in.FailOnConstraintViolation, &out.FailOnConstraintViolation
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchStrategy.
func (in *MatchStrategy) DeepCopy() *MatchStrategy {
	if in == nil {
		return nil
	}
	out := new(MatchStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryLimits) DeepCopyInto(out *MemoryLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryLimits.
func (in *MemoryLimits) DeepCopy() *MemoryLimits {
	if in == nil {
		return nil
	}
	out := new(MemoryLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceDetection) DeepCopyInto(out *NamespaceDetection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceDetection.
func (in *NamespaceDetection) DeepCopy() *NamespaceDetection {
	if in == nil {
		return nil
	}
	out := new(NamespaceDetection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerformanceConfig) DeepCopyInto(out *PerformanceConfig) {
	*out = *in
	if in.RequestTimeout != nil {
		in, out := &in.RequestTimeout, &out.RequestTimeout
		*out = new(string)
		**out = **in
	}
	if in.MemoryLimits != nil {
		in, out := &in.MemoryLimits, &out.MemoryLimits
		*out = new(MemoryLimits)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerformanceConfig.
func (in *PerformanceConfig) DeepCopy() *PerformanceConfig {
	if in == nil {
		return nil
	}
	out := new(PerformanceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReferencePattern) DeepCopyInto(out *ReferencePattern) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReferencePattern.
func (in *ReferencePattern) DeepCopy() *ReferencePattern {
	if in == nil {
		return nil
	}
	out := new(ReferencePattern)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReferenceResolutionConfig) DeepCopyInto(out *ReferenceResolutionConfig) {
	*out = *in
	if in.AdditionalPatterns != nil {
		in, out := &in.AdditionalPatterns, &out.AdditionalPatterns
		*out = make([]ReferencePattern, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReferenceResolutionConfig.
func (in *ReferenceResolutionConfig) DeepCopy() *ReferenceResolutionConfig {
	if in == nil {
		return nil
	}
	out := new(ReferenceResolutionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRequest) DeepCopyInto(out *ResourceRequest) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(MatchStrategy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRequest.
func (in *ResourceRequest) DeepCopy() *ResourceRequest {
	if in == nil {
		return nil
	}
	out := new(ResourceRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScopeFilterConfig) DeepCopyInto(out *ScopeFilterConfig) {
	*out = *in
	if in.IncludeAPIGroups != nil {
		in, out := &in.IncludeAPIGroups, &out.IncludeAPIGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeAPIGroups != nil {
		in, out := &in.ExcludeAPIGroups, &out.ExcludeAPIGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IncludeKinds != nil {
		in, out := &in.IncludeKinds, &out.IncludeKinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeKinds != nil {
		in, out := &in.ExcludeKinds, &out.ExcludeKinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IncludeNamespaces != nil {
		in, out := &in.IncludeNamespaces, &out.IncludeNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeNamespaces != nil {
		in, out := &in.ExcludeNamespaces, &out.ExcludeNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScopeFilterConfig.
func (in *ScopeFilterConfig) DeepCopy() *ScopeFilterConfig {
	if in == nil {
		return nil
	}
	out := new(ScopeFilterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Selector) DeepCopyInto(out *Selector) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = new(LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Expressions != nil {
		in, out := &in.Expressions, &out.Expressions
		*out = make([]Expression, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CrossNamespace != nil {
		in, out := &in.CrossNamespace, &out.CrossNamespace
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Selector.
func (in *Selector) DeepCopy() *Selector {
	if in == nil {
		return nil
	}
	out := new(Selector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SortCriteria) DeepCopyInto(out *SortCriteria) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SortCriteria.
func (in *SortCriteria) DeepCopy() *SortCriteria {
	if in == nil {
		return nil
	}
	out := new(SortCriteria)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransformOptions) DeepCopyInto(out *TransformOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransformOptions.
func (in *TransformOptions) DeepCopy() *TransformOptions {
	if in == nil {
		return nil
	}
	out := new(TransformOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TraversalConfig) DeepCopyInto(out *TraversalConfig) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(string)
		**out = **in
	}
	if in.ScopeFilter != nil {
		in, out := &in.ScopeFilter, &out.ScopeFilter
		*out = new(ScopeFilterConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.BatchConfig != nil {
		in, out := &in.BatchConfig, &out.BatchConfig
		*out = new(BatchConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CacheConfig != nil {
		in, out := &in.CacheConfig, &out.CacheConfig
		*out = new(CacheConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ReferenceResolution != nil {
		in, out := &in.ReferenceResolution, &out.ReferenceResolution
		*out = new(ReferenceResolutionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CycleHandling != nil {
		in, out := &in.CycleHandling, &out.CycleHandling
		*out = new(CycleHandlingConfig)
		**out = **in
	}
	if in.Performance != nil {
		in, out := &in.Performance, &out.Performance
		*out = new(PerformanceConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TraversalConfig.
func (in *TraversalConfig) DeepCopy() *TraversalConfig {
	if in == nil {
		return nil
	}
	out := new(TraversalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XRLabelConfig) DeepCopyInto(out *XRLabelConfig) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DynamicLabels != nil {
		in, out := &in.DynamicLabels, &out.DynamicLabels
		*out = make([]DynamicLabel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NamespaceDetection != nil {
		in, out := &in.NamespaceDetection, &out.NamespaceDetection
		*out = new(NamespaceDetection)
		**out = **in
	}
	if in.EnforceLabels != nil {
		in, out := &in.EnforceLabels, &out.EnforceLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XRLabelConfig.
func (in *XRLabelConfig) DeepCopy() *XRLabelConfig {
	if in == nil {
		return nil
	}
	out := new(XRLabelConfig)
	in.DeepCopyInto(out)
	return out
}
